// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: queue_console

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_TextAreaSSID = NULL;
lv_obj_t * ui_TextAreaPassword = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_ButtonSave = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_ButtonReturn = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_TextAreaStatus = NULL;
lv_obj_t * ui_LabelApp = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_TextAreaCDown1 = NULL;
lv_obj_t * ui_TextAreaCDown2 = NULL;
lv_obj_t * ui_TextAreaMAC1 = NULL;
lv_obj_t * ui_TextAreaMAC2 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label20 = NULL;
// event funtions
void ui_event_TextAreaSSID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextAreaSSID);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_TextAreaPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextAreaPassword);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ButtonSave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CALLBACK_SAVE(e);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ButtonReturn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_TextAreaCDown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextAreaCDown1);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_TextAreaCDown2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextAreaCDown2);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_TextAreaMAC1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextAreaMAC1);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_TextAreaMAC2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextAreaMAC2);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen2, &ui_font_ALLFONT14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -220);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Timer Console Settings");
    lv_obj_set_style_text_decor(ui_Label8, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaSSID = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextAreaSSID, 260);
    lv_obj_set_height(ui_TextAreaSSID, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_TextAreaSSID, -263);
    lv_obj_set_y(ui_TextAreaSSID, -152);
    lv_obj_set_align(ui_TextAreaSSID, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaSSID, "SSID");
    lv_textarea_set_one_line(ui_TextAreaSSID, true);
    lv_obj_set_style_text_font(ui_TextAreaSSID, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TextAreaSSID, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaSSID, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaSSID, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaSSID, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(ui_TextAreaSSID, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_TextAreaPassword = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextAreaPassword, 260);
    lv_obj_set_height(ui_TextAreaPassword, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_TextAreaPassword, -262);
    lv_obj_set_y(ui_TextAreaPassword, -74);
    lv_obj_set_align(ui_TextAreaPassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaPassword, "Password");
    lv_textarea_set_one_line(ui_TextAreaPassword, true);
    lv_obj_set_style_text_font(ui_TextAreaPassword, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TextAreaPassword, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaPassword, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaPassword, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaPassword, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(ui_TextAreaPassword, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -345);
    lv_obj_set_y(ui_Label9, -182);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "WiFi SSID");

    ui_Label10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -330);
    lv_obj_set_y(ui_Label10, -108);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "WiFi Password");

    ui_Label11 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 255);
    lv_obj_set_y(ui_Label11, -182);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "MAC Address 1");

    ui_Label12 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 259);
    lv_obj_set_y(ui_Label12, -108);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "MAC Address 2");

    ui_ButtonSave = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonSave, 180);
    lv_obj_set_height(ui_ButtonSave, 43);
    lv_obj_set_x(ui_ButtonSave, 296);
    lv_obj_set_y(ui_ButtonSave, -16);
    lv_obj_set_align(ui_ButtonSave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonSave, lv_color_hex(0x08DA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_ButtonSave);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "SAVE");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonReturn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonReturn, 151);
    lv_obj_set_height(ui_ButtonReturn, 43);
    lv_obj_set_x(ui_ButtonReturn, 254);
    lv_obj_set_y(ui_ButtonReturn, 180);
    lv_obj_set_align(ui_ButtonReturn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReturn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonReturn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 253);
    lv_obj_set_y(ui_Label14, 181);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "RETURN");

    ui_Label15 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -322);
    lv_obj_set_y(ui_Label15, 14);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Status - Info");

    ui_TextAreaStatus = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextAreaStatus, 460);
    lv_obj_set_height(ui_TextAreaStatus, 174);
    lv_obj_set_x(ui_TextAreaStatus, -140);
    lv_obj_set_y(ui_TextAreaStatus, 114);
    lv_obj_set_align(ui_TextAreaStatus, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaStatus, "Placeholder...");

    ui_LabelApp = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelApp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelApp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelApp, -251);
    lv_obj_set_y(ui_LabelApp, 216);
    lv_obj_set_align(ui_LabelApp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelApp, "Queue Console - www.rousis.gr");
    lv_obj_set_style_text_decor(ui_LabelApp, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen2);
    lv_obj_set_width(ui_Keyboard1, 773);
    lv_obj_set_height(ui_Keyboard1, 225);
    lv_obj_set_x(ui_Keyboard1, -3);
    lv_obj_set_y(ui_Keyboard1, 124);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0xB6B6B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Keyboard1, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_TextAreaCDown1 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextAreaCDown1, 172);
    lv_obj_set_height(ui_TextAreaCDown1, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_TextAreaCDown1, 4);
    lv_obj_set_y(ui_TextAreaCDown1, -152);
    lv_obj_set_align(ui_TextAreaCDown1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaCDown1, "00:00:00");
    lv_obj_set_style_text_align(ui_TextAreaCDown1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaCDown1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TextAreaCDown1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaCDown1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaCDown1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaCDown1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaCDown2 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextAreaCDown2, 172);
    lv_obj_set_height(ui_TextAreaCDown2, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_TextAreaCDown2, 6);
    lv_obj_set_y(ui_TextAreaCDown2, -74);
    lv_obj_set_align(ui_TextAreaCDown2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaCDown2, "00:00:00");
    lv_obj_set_style_text_align(ui_TextAreaCDown2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaCDown2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TextAreaCDown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaCDown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaCDown2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaCDown2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaMAC1 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextAreaMAC1, 260);
    lv_obj_set_height(ui_TextAreaMAC1, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_TextAreaMAC1, 255);
    lv_obj_set_y(ui_TextAreaMAC1, -152);
    lv_obj_set_align(ui_TextAreaMAC1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaMAC1, "XX:XX:XX:XX");
    lv_obj_set_style_text_align(ui_TextAreaMAC1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaMAC1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TextAreaMAC1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaMAC1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaMAC1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaMAC1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaMAC2 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextAreaMAC2, 260);
    lv_obj_set_height(ui_TextAreaMAC2, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_TextAreaMAC2, 255);
    lv_obj_set_y(ui_TextAreaMAC2, -74);
    lv_obj_set_align(ui_TextAreaMAC2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaMAC2, "XX:XX:XX:XX");
    lv_obj_set_style_text_align(ui_TextAreaMAC2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaMAC2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TextAreaMAC2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaMAC2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaMAC2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaMAC2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 1);
    lv_obj_set_y(ui_Label19, -182);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Cuntdown (CDown) 1 set:");

    ui_Label20 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 7);
    lv_obj_set_y(ui_Label20, -108);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Cuntdown (CDown) 2 set:");

    lv_obj_add_event_cb(ui_TextAreaSSID, ui_event_TextAreaSSID, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaPassword, ui_event_TextAreaPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSave, ui_event_ButtonSave, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonReturn, ui_event_ButtonReturn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaCDown1, ui_event_TextAreaCDown1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaCDown2, ui_event_TextAreaCDown2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaMAC1, ui_event_TextAreaMAC1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaMAC2, ui_event_TextAreaMAC2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Label8 = NULL;
    ui_TextAreaSSID = NULL;
    ui_TextAreaPassword = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_ButtonSave = NULL;
    ui_Label13 = NULL;
    ui_ButtonReturn = NULL;
    ui_Label14 = NULL;
    ui_Label15 = NULL;
    ui_TextAreaStatus = NULL;
    ui_LabelApp = NULL;
    ui_Keyboard1 = NULL;
    ui_TextAreaCDown1 = NULL;
    ui_TextAreaCDown2 = NULL;
    ui_TextAreaMAC1 = NULL;
    ui_TextAreaMAC2 = NULL;
    ui_Label19 = NULL;
    ui_Label20 = NULL;

}
