// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: queue_console

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_QueueText;
extern void ui_event_Player1(lv_event_t * e);
extern lv_obj_t * ui_Player1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_PanelConnection;
extern lv_obj_t * ui_Label7;
extern void ui_event_Player2(lv_event_t * e);
extern lv_obj_t * ui_Player2;
extern lv_obj_t * ui_Label1;
extern void ui_event_Player3(lv_event_t * e);
extern lv_obj_t * ui_Player3;
extern lv_obj_t * ui_Label2;
extern void ui_event_Player4(lv_event_t * e);
extern lv_obj_t * ui_Player4;
extern lv_obj_t * ui_Label4;
extern void ui_event_Player5(lv_event_t * e);
extern lv_obj_t * ui_Player5;
extern lv_obj_t * ui_Label5;
extern void ui_event_Player6(lv_event_t * e);
extern lv_obj_t * ui_Player6;
extern lv_obj_t * ui_Label6;
extern void ui_event_Player7(lv_event_t * e);
extern lv_obj_t * ui_Player7;
extern lv_obj_t * ui_Label16;
extern void ui_event_Player8(lv_event_t * e);
extern lv_obj_t * ui_Player8;
extern lv_obj_t * ui_Label17;
extern void ui_event_Player9(lv_event_t * e);
extern lv_obj_t * ui_Player9;
extern lv_obj_t * ui_Label18;
extern void ui_event_Player10(lv_event_t * e);
extern lv_obj_t * ui_Player10;
extern lv_obj_t * ui_Label21;
extern void ui_event_Player11(lv_event_t * e);
extern lv_obj_t * ui_Player11;
extern lv_obj_t * ui_Label22;
extern void ui_event_Player12(lv_event_t * e);
extern lv_obj_t * ui_Player12;
extern lv_obj_t * ui_Label23;
extern void ui_event_Player13(lv_event_t * e);
extern lv_obj_t * ui_Player13;
extern lv_obj_t * ui_Label24;
extern void ui_event_Player14(lv_event_t * e);
extern lv_obj_t * ui_Player14;
extern lv_obj_t * ui_Label25;
extern void ui_event_Player15(lv_event_t * e);
extern lv_obj_t * ui_Player15;
extern lv_obj_t * ui_Label26;
extern void ui_event_Player16(lv_event_t * e);
extern lv_obj_t * ui_Player16;
extern lv_obj_t * ui_Label27;
extern void ui_event_Player17(lv_event_t * e);
extern lv_obj_t * ui_Player17;
extern lv_obj_t * ui_Label28;
extern void ui_event_Player18(lv_event_t * e);
extern lv_obj_t * ui_Player18;
extern lv_obj_t * ui_Label29;
extern void ui_event_Player19(lv_event_t * e);
extern lv_obj_t * ui_Player19;
extern lv_obj_t * ui_Label30;
extern void ui_event_Player20(lv_event_t * e);
extern lv_obj_t * ui_Player20;
extern lv_obj_t * ui_Label31;
extern void ui_event_Player21(lv_event_t * e);
extern lv_obj_t * ui_Player21;
extern lv_obj_t * ui_Label32;
extern void ui_event_Player22(lv_event_t * e);
extern lv_obj_t * ui_Player22;
extern lv_obj_t * ui_Label33;
extern void ui_event_Player23(lv_event_t * e);
extern lv_obj_t * ui_Player23;
extern lv_obj_t * ui_Label34;
extern void ui_event_Player24(lv_event_t * e);
extern lv_obj_t * ui_Player24;
extern lv_obj_t * ui_Label35;
extern void ui_event_NEW_GAME(lv_event_t * e);
extern lv_obj_t * ui_NEW_GAME;
extern lv_obj_t * ui_Label36;
extern void ui_event_NEW_GAME1(lv_event_t * e);
extern lv_obj_t * ui_NEW_GAME1;
extern lv_obj_t * ui_Label37;
extern void ui_event_SwitchExit(lv_event_t * e);
extern lv_obj_t * ui_SwitchExit;
extern lv_obj_t * ui_Label38;
extern void ui_event_SwitchGame(lv_event_t * e);
extern lv_obj_t * ui_SwitchGame;
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_guest;
extern lv_obj_t * ui_QueueText1;
extern lv_obj_t * ui_QueueText2;
extern lv_obj_t * ui_QueueText3;
extern lv_obj_t * ui_QueueText4;
extern void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern void ui_event_inc(lv_event_t * e);
extern lv_obj_t * ui_inc;
extern lv_obj_t * ui_Label39;
extern void ui_event_dec(lv_event_t * e);
extern lv_obj_t * ui_dec;
extern lv_obj_t * ui_Label40;
extern void ui_event_inc1(lv_event_t * e);
extern lv_obj_t * ui_inc1;
extern lv_obj_t * ui_Label41;
extern void ui_event_dec1(lv_event_t * e);
extern lv_obj_t * ui_dec1;
extern lv_obj_t * ui_Label42;
extern void ui_event_inc2(lv_event_t * e);
extern lv_obj_t * ui_inc2;
extern lv_obj_t * ui_Label43;
extern void ui_event_dec2(lv_event_t * e);
extern lv_obj_t * ui_dec2;
extern lv_obj_t * ui_Label44;
extern void ui_event_inc3(lv_event_t * e);
extern lv_obj_t * ui_inc3;
extern lv_obj_t * ui_Label45;
extern void ui_event_dec3(lv_event_t * e);
extern lv_obj_t * ui_dec3;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_home1;
extern lv_obj_t * ui_QueueText5;
extern void ui_event_inc4(lv_event_t * e);
extern lv_obj_t * ui_inc4;
extern lv_obj_t * ui_Label47;
extern void ui_event_dec4(lv_event_t * e);
extern lv_obj_t * ui_dec4;
extern lv_obj_t * ui_Label48;
extern void ui_event_NEW_GAME3(lv_event_t * e);
extern lv_obj_t * ui_NEW_GAME3;
extern lv_obj_t * ui_Label49;
extern void ui_event_NEW_GAME4(lv_event_t * e);
extern lv_obj_t * ui_NEW_GAME4;
extern lv_obj_t * ui_Label50;
extern void ui_event_NEW_GAME5(lv_event_t * e);
extern lv_obj_t * ui_NEW_GAME5;
extern lv_obj_t * ui_Label51;
extern void ui_event_NEW_GAME6(lv_event_t * e);
extern lv_obj_t * ui_NEW_GAME6;
extern lv_obj_t * ui_Label52;
extern void ui_event_NEW_GAME7(lv_event_t * e);
extern lv_obj_t * ui_NEW_GAME7;
extern lv_obj_t * ui_Label53;
extern void ui_event_inc5(lv_event_t * e);
extern lv_obj_t * ui_inc5;
extern lv_obj_t * ui_Label54;
extern void ui_event_dec5(lv_event_t * e);
extern lv_obj_t * ui_dec5;
extern lv_obj_t * ui_Label55;
extern void ui_event_dec6(lv_event_t * e);
extern lv_obj_t * ui_dec6;
extern lv_obj_t * ui_Label56;
extern void ui_event_inc6(lv_event_t * e);
extern lv_obj_t * ui_inc6;
extern lv_obj_t * ui_Label57;
extern void ui_event_inc7(lv_event_t * e);
extern lv_obj_t * ui_inc7;
extern lv_obj_t * ui_Label58;
extern void ui_event_inc8(lv_event_t * e);
extern lv_obj_t * ui_inc8;
extern lv_obj_t * ui_Label59;
extern void ui_event_inc9(lv_event_t * e);
extern lv_obj_t * ui_inc9;
extern lv_obj_t * ui_Label60;
extern void ui_event_inc10(lv_event_t * e);
extern lv_obj_t * ui_inc10;
extern lv_obj_t * ui_Label61;
extern void ui_event_inc11(lv_event_t * e);
extern lv_obj_t * ui_inc11;
extern lv_obj_t * ui_Label62;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Connected;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

