// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: queue_console

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label8;
extern void ui_event_TextAreaSSID(lv_event_t * e);
extern lv_obj_t * ui_TextAreaSSID;
extern void ui_event_TextAreaPassword(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPassword;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern void ui_event_ButtonSave(lv_event_t * e);
extern lv_obj_t * ui_ButtonSave;
extern lv_obj_t * ui_Label13;
extern void ui_event_ButtonReturn(lv_event_t * e);
extern lv_obj_t * ui_ButtonReturn;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_TextAreaStatus;
extern lv_obj_t * ui_LabelApp;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_TextAreaCDown1(lv_event_t * e);
extern lv_obj_t * ui_TextAreaCDown1;
extern void ui_event_TextAreaCDown2(lv_event_t * e);
extern lv_obj_t * ui_TextAreaCDown2;
extern void ui_event_TextAreaMAC1(lv_event_t * e);
extern lv_obj_t * ui_TextAreaMAC1;
extern void ui_event_TextAreaMAC2(lv_event_t * e);
extern lv_obj_t * ui_TextAreaMAC2;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

