// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: queue_console

#ifndef _QUEUE_CONSOLE_UI_H
#define _QUEUE_CONSOLE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1188446250);    // assets/Time (9).png
LV_IMG_DECLARE(ui_img_sett_png);    // assets/sett.png
LV_IMG_DECLARE(ui_img_1269516485);    // assets/Time (8).png
LV_IMG_DECLARE(ui_img_vb_logo_png);    // assets/VB_logo.png

// FONTS
LV_FONT_DECLARE(ui_font_ALLFONT14);
LV_FONT_DECLARE(ui_font_CanvaSans14);
LV_FONT_DECLARE(ui_font_CanvaSans20);
LV_FONT_DECLARE(ui_font_CanvaSans30);
LV_FONT_DECLARE(ui_font_CanvaSans48);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
