// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: queue_console

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void CALLBACK_P1(lv_event_t * e);
void CALLBACK_P2(lv_event_t * e);
void CALLBACK_P3(lv_event_t * e);
void CALLBACK_P4(lv_event_t * e);
void CALLBACK_P5(lv_event_t * e);
void CALLBACK_P6(lv_event_t * e);
void CALLBACK_P7(lv_event_t * e);
void CALLBACK_P8(lv_event_t * e);
void CALLBACK_P9(lv_event_t * e);
void CALLBACK_P10(lv_event_t * e);
void CALLBACK_P11(lv_event_t * e);
void CALLBACK_P12(lv_event_t * e);
void CALLBACK_P13(lv_event_t * e);
void CALLBACK_P14(lv_event_t * e);
void CALLBACK_P15(lv_event_t * e);
void CALLBACK_P16(lv_event_t * e);
void CALLBACK_P17(lv_event_t * e);
void CALLBACK_P18(lv_event_t * e);
void CALLBACK_P19(lv_event_t * e);
void CALLBACK_P20(lv_event_t * e);
void CALLBACK_P21(lv_event_t * e);
void CALLBACK_P23(lv_event_t * e);
void CALLBACK_P22(lv_event_t * e);
void CALLBACK_NEW_GAME(lv_event_t * e);
void CB_buzzer(lv_event_t * e);
void CALLBACK_EXIT(lv_event_t * e);
void CB_GameON(lv_event_t * e);
void CB_TF_ENABLE(lv_event_t * e);
void CB_TF1_P1(lv_event_t * e);
void CB_TF1_M1(lv_event_t * e);
void CB_TF2_P1(lv_event_t * e);
void CB_TF2_M1(lv_event_t * e);
void CB_TF3_P1(lv_event_t * e);
void CB_TF3_M1(lv_event_t * e);
void CB_TF4_P1(lv_event_t * e);
void CB_TF4_M1(lv_event_t * e);
void CALLBACK_PERIOD_P(lv_event_t * e);
void CALLBACK_PERIOD_m(lv_event_t * e);
void CALLBACK_SHOTCLK_24(lv_event_t * e);
void CALLBACK_SHOTCLK_14(lv_event_t * e);
void CALLBACK_SHOTCLK_Set(lv_event_t * e);
void CALLBACK_START_STOP(lv_event_t * e);
void CALLBACK_SET(lv_event_t * e);
void CB_Home_P1(lv_event_t * e);
void CB_Home_M1(lv_event_t * e);
void CB_Guest_m1(lv_event_t * e);
void CB_Home_P2(lv_event_t * e);
void CB_Home_P3(lv_event_t * e);
void CB_Guest_P1(lv_event_t * e);
void CB_Guest_P2(lv_event_t * e);
void CB_Guest_P3(lv_event_t * e);
void CALLBACK_STOP(lv_event_t * e);
void CALLBACK_SAVE(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
