// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: queue_console

#include "ui.h"

bool CHK_Flag = false;
int CHK_Val = 0;

// bool CHK_Flag_Func(void);
// int CHK_Val_Func(void);

bool CHK_Flag_Func(void) {
	return CHK_Flag;
}

int CHK_Val_Func(void) {
	CHK_Flag = false;
	return CHK_Val;
}



void CALLBACK_SAVE(lv_event_t* e) {
	CHK_Flag = true;
	CHK_Val = 25;
	// Your code here
}

void CALLBACK_STOP(lv_event_t* e) {
	CHK_Flag = true;
	CHK_Val = 26;
	// Your code here
}


void CALLBACK_P1(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 1;
	// Your code here
}

void CALLBACK_P2(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 2;
	// Your code here
}

void CALLBACK_P3(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 3;
	// Your code here
}

void CALLBACK_P4(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 4;
	// Your code here
}

void CALLBACK_P5(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 5;
	// Your code here
}

void CALLBACK_P6(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 6;
	// Your code here
}

void CALLBACK_P7(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 7;
	// Your code here
}

void CALLBACK_P8(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 8;
	// Your code here
}

void CALLBACK_P9(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 9;
	// Your code here
}

void CALLBACK_P10(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 10;
	// Your code here
}

void CALLBACK_P11(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 11;
	// Your code here
}

void CALLBACK_P12(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 12;
	// Your code here
}

void CALLBACK_P13(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 13;
	// Your code here
}

void CALLBACK_P14(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 14;
	// Your code here
}

void CALLBACK_P15(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 15;
	// Your code here
}

void CALLBACK_P16(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 16;
	// Your code here
}

void CALLBACK_P17(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 17;
	// Your code here
}

void CALLBACK_P18(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 18;
	// Your code here
}

void CALLBACK_P19(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 19;
	// Your code here
}

void CALLBACK_P20(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 20;
	// Your code here
}

void CALLBACK_P21(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 21;
	// Your code here
}

void CALLBACK_P22(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 22;
	// Your code here
}

void CALLBACK_P23(lv_event_t * e)
{
				CHK_Flag = true;
	CHK_Val = 23;
	// Your code here
}

void CALLBACK_P24(lv_event_t * e)
{
				CHK_Flag = true;
	CHK_Val = 24;
	// Your code here
}
void CALLBACK_NEW_GAME(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 25;
	// Your code here
}

void CB_buzzer(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 26;
	// Your code here
}

void CALLBACK_EXIT(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 27;
	// Your code here
}

void CB_GameON(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 28;
	// Your code here
}

void CB_TF_ENABLE(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 29;
	// Your code here
}

void CB_TF1_P1(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 30;
	// Your code here
}

void CB_TF1_M1(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 31;
	// Your code here
}

void CB_TF2_P1(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 32;
	// Your code here
}

void CB_TF2_M1(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 33;
	// Your code here
}

void CB_TF3_P1(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 34;
	// Your code here
}

void CB_TF3_M1(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 35;
	// Your code here
}

void CB_TF4_P1(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 36;
	// Your code here
}

void CB_TF4_M1(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 37;
	// Your code here
}

void CALLBACK_PERIOD_P(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 38;
	// Your code here
}

void CALLBACK_PERIOD_m(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 39;
	// Your code here
}

void CALLBACK_SHOTCLK_24(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 40;
	// Your code here
}

void CALLBACK_SHOTCLK_14(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 41;
	// Your code here
}

void CALLBACK_SHOTCLK_Set(lv_event_t* e) {
		CHK_Flag = true;
	CHK_Val = 42;
	// Your code here
}

void CALLBACK_START_STOP(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 43;
	// Your code here
}

void CALLBACK_SET(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 44;
	// Your code here
}

void CB_Home_P1(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 45;
	// Your code here
}

void CB_Home_M1(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 46;
	// Your code here
}

void CB_Guest_m1(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 47;
	// Your code here
}

void CB_Home_P2(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 48;
	// Your code here
}

void CB_Home_P3(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 49;
	// Your code here
}

void CB_Guest_P1(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 50;
	// Your code here
}

void CB_Guest_P2(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 51;
	// Your code here
}

void CB_Guest_P3(lv_event_t* e) {
			CHK_Flag = true;
	CHK_Val = 52;
	// Your code here
}


